name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar testes
        run: pytest --cov

  build:
    needs: test
    strategy:
      matrix:
        include:
          - os: windows-latest
            output: main.exe
            asset_name: python-pygame-runner-windows.exe

          - os: ubuntu-latest
            output: main
            asset_name: python-pygame-runner-linux

          - os: macos-latest
            output: main
            asset_name: python-pygame-runner-mac

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar libs SDL2 (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pkg-config \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libsdl2-gfx-dev \
            python3-dev

      - name: Instalar dependências de build
        run: pip install pyinstaller pygame-ce==2.5.7

      - name: Gerar executável
        run: pyinstaller --onefile --windowed main.py

      - name: Renomear executável
        shell: bash
        run: mv dist/${{ matrix.output }} dist/${{ matrix.asset_name }}

      - name: Publicar na Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/${{ matrix.asset_name }}
